### ISSUE TITLE
[Feature request] export layerStyles

### ISSUE THREAD

**Issue by Pausansol** [zeplin/zeplin-sketch-plugin#45]
We would like to be able to expose the layerStyles of a layer defined in Sketch and be able to communicate them to the engineering teams.

**Comment by yceballost** [comment]
+1

**Comment by borulday** [comment]
Hi, I'm closing this issue because it has been outdated.

Currently, Zeplin collects the layer style data to display it on the right panel.

<img width="350" alt="Screen Shot 2022-03-23 at 16 44 17" src="https://user-images.githubusercontent.com/1013604/159713940-a7ae39e7-6103-40d9-84df-d7d18fef244f.png">

Please send your feedback and feature requests directly to [support@zeplin.io](mailto:support@zeplin.io)

Thank you!
