### ISSUE TITLE
[Feature request] Allow Run plugin for sketchtool for CI environments upload

### ISSUE THREAD

**Issue by oscarcv** [zeplin/zeplin-sketch-plugin#48]
We are trying to upload automatically through continuous integration and it would be interesting to be able to upload new versions from the command line automatically. If there are currently no public apis at least you can upload them from the command line by running the plugin

**Comment by yceballost** [comment]
+1

**Comment by borulday** [comment]
Hi, I'm closing this issue because it has been outdated.

[Zeplin Public API](https://docs.zeplin.dev/docs) has no export ability for now and it would be great to build an automated export flow after adding this ability to the API. We'll brainstorm about it!

Please send your feedback and feature requests directly to [support@zeplin.io](mailto:support@zeplin.io)

Thank you!
