### ISSUE TITLE
Could not communicate with the plugin

### ISSUE THREAD

**Issue by murliv-design** [zeplin/zeplin-sketch-plugin#58]
Could not communicate with the plugin

This panel communicates with a plugin to export the designs, but looks like it’s not properly installed automatically.

Please follow the guide [here](https://support.zeplin.io/en/articles/245806-installing-photoshop-plugin-on-mac) to manually install it.

![Screenshot 2024-12-11 at 1 30 02 PM](https://github.com/user-attachments/assets/e7b3748f-11cc-402d-8403-9f977995029b)

**Comment by borulday** [comment]
Hi @murliv-design, thank you for reaching out, and I’m sorry to hear about the issue you’re experiencing with the Photoshop plugin. This repository (`zeplin-sketch-plugin`) is specifically for Zeplin’s Sketch integration, so I’ll be closing this issue here.

To get further assistance with the Photoshop plugin, could you please reach out to our support team at support@zeplin.io? They’ll be happy to help you resolve this issue. Thanks!
